# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessenger.proto\"\x1a\n\nClientInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x10\x43onnectionStatus\x12\x11\n\tconnected\x18\x01 \x01(\x08\"<\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\x83\x01\n\tMessenger\x12+\n\x07\x43onnect\x12\x0b.ClientInfo\x1a\x11.ConnectionStatus\"\x00\x12!\n\x0bSendMessage\x12\x08.Message\x1a\x06.Empty\"\x00\x12&\n\x0eReceiveMessage\x12\x06.Empty\x1a\x08.Message\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messenger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTINFO']._serialized_start=19
  _globals['_CLIENTINFO']._serialized_end=45
  _globals['_CONNECTIONSTATUS']._serialized_start=47
  _globals['_CONNECTIONSTATUS']._serialized_end=84
  _globals['_MESSAGE']._serialized_start=86
  _globals['_MESSAGE']._serialized_end=146
  _globals['_EMPTY']._serialized_start=148
  _globals['_EMPTY']._serialized_end=155
  _globals['_MESSENGER']._serialized_start=158
  _globals['_MESSENGER']._serialized_end=289
# @@protoc_insertion_point(module_scope)
